version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Run Danger CI
          command: npx danger ci
      - run:
          name: Start Express server
          command: |
            nohup npm start &

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            pull_requests:
              only:
                - master  # Ensure this is only run on PRs to master
