version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14  # Using Node.js 14 as the base Docker image
    working_directory: ~/repo  # Directory inside the container

jobs:
  build:
    executor: node-executor
    steps:
      - checkout  # Checkout the code from the repository
      - run:
          name: Install dependencies
          command: npm install  # Install dependencies
      - run:
          name: Run tests
          command: npm test  # Run the tests
      - run:
          name: Run Danger CI
          command: npx danger ci  # Run Danger CI to check PR status
      - run:
          name: Start Express server
          command: |
            nohup npm start &  # Start the server in the background (non-blocking)

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            pull_requests:
              only:
                - master  # This ensures it only runs for PRs targeting the 'master' branch
